[package]
name = "gm81_yyd_hook"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
crc = "1.8"
crossbeam-channel = "0.5"
crossbeam-utils = "0.8"
ctor = "0.1.20"
image = { version = "0.23", default-features = false, features = ["png"] }
itertools = "0.10"
paste = "1.0"
phf = { version = "0.7.24", features = ["macros"] }
png = "0.16"
rayon = "1.5"
winapi = { version = "0.3.9", features = ["memoryapi", "processthreadsapi"] }
