cargo-features = ['strip']

[package]
name = "gm82save"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
lto = true
strip = true
panic = "abort"

[dependencies]
crc = "1.8"
crossbeam-channel = "0.5"
crossbeam-utils = "0.8"
ctor = "0.1.20"
itertools = "0.10"
paste = "1.0"
png = "0.16"
rayon = "1.5"
