[package]
name = "gm81_yyd_hook"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
ctor = "0.1.20"
image = "0.23.14"
phf = { version = "0.7.24", features = ["macros"] }
winapi = { version = "0.3.9", features = ["memoryapi", "processthreadsapi"] }
