cargo-features = ['strip']

[package]
name = "gm82save"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
default = ["smooth_progress_bar"]
smooth_progress_bar = ["crossbeam-channel"]

[profile.release]
codegen-units = 1
lto = true
strip = true
panic = "abort"

[build-dependencies]
time = "0.3"

[dependencies]
crc = "1.8"
crossbeam-channel = {version = "0.5", optional = true}
ctor = "0.1.20"
flate2 = {version = "1.0", features = ["zlib-ng-compat"], default-features = false}
itertools = "0.10"
paste = "1.0"
png = "0.16"
rayon = "1.5"
unicase = "2.6"
