name: Rust

on:
  push:
  pull_request:
  workflow_dispatch: {}

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        target: i686-pc-windows-msvc
        toolchain: nightly
        default: true
    - name: Build
      run: cargo build --release --verbose
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: gm82save
        path: target/i686-pc-windows-msvc/release/gm82save.dll
